name: story_reading_app
description: Offline story reader using build-time books.json
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  archive: ^3.6.1
  flutter_riverpod: ^3.0.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/books.json
    - assets/books/
    - assets/books/a/
    - assets/books/a/chapters/
    - assets/books/b/
    - assets/books/b/chapters/
    - assets/books/c/
    - assets/books/c/chapters/
    - assets/books/d/
    - assets/books/d/chapters/
    - assets/books/e/
    - assets/books/e/chapters/
    - assets/books/e/
    - assets/books/e/chapters/
    - assets/books/book_a/
    - assets/books/book_a/chapters/
    - assets/books/book_b/
    - assets/books/book_b/chapters/
    - assets/icons/
    - assets/images/
    - assets/colors/

flutter_gen:
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml